### PR TITLE
Simplify process cleanup by killing process group

### PR DESCRIPTION
**Pull request by fatso83**
Hi, Morgan. 
Worked on the process cleanup over the weekend. This easy fix took some time since I never got anywhere with the `pkill` command after endless variations.

This approach is simpler, as it will kill all the processes started by the script.

### CODE REVIEW

**Comment by mroderick** [comment]
Thank you for the pull request.

`npm test` fails on my OSX 10.11

```
./scripts/ci-test.sh: line 13: kill: (-16704) - No such process
npm ERR! Test failed.  See above for more details.
```

Any ideas?

**Comment by fatso83** [comment]
:flushed: That was embarrassing. It worked when I ran the script in unison, but I was staying up so late that I forgot to test using `npm test`. And when you run the script using `npm test` the parent group id is that of `npm`, not the shell script, so that did not work.

I'll push a fix.

**Comment by fatso83** [comment]
Works for you now? The only negative I could see is that you get a "Terminated: 15" message when run with `npm test`

**Comment by mroderick** [comment]
It works for me. I'll merge it and we'll see what Travis can do with it

**Pull request merged**
